### ISSUE TITLE
KeyError while consuming interface

### ISSUE THREAD

**Issue by Hong-Chang** [CentaurusInfra/mizar#611] opened 2022-02-03 20:35 UTC
Occasionally pod creation keep failing. I checked log from the first failure and got following error message:
2022-02-03 20:07:04 INFO     Consuming interfaces for pod: vmdefault-default-system Current Queue: ['kube-dns-554c5866fc-mdgth-kube-system-system', 'coredns-default-5b4f9674cf-74blj-kube-system-system']
2022-02-03 20:07:04 ERROR    Exception calling application: 'vmdefault-default-system'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/usr/local/lib/python3.9/site-packages/mizar/daemon/interface_service.py", line 211, in ConsumeInterfaces
    if self.pod_dict[requested_pod_name]:
KeyError: 'vmdefault-default-system'

The issue:
in mizar/daemon/interface_service.py, func ConsumeInterfaces, originally there is a "while" loop to wait for interface has been initialized. Currently the while loop is gone and when interface is not ready, pod_dict dict won't have needed key/value pair, hence throw the error.

**Comment by yb01** [comment] 2022-02-04 18:05
we think this is the cause for VM pod failures randomly. so please let's fix this issue as soon as we can just in case our suspection is incorrect.

**Comment by phudtran** [comment] 2022-02-04 19:29
Fixed in #612

**Closed as completed by phudtran** 2022-02-04 19:29 UTC
